import os
from os import path
os.makedirs(name="LEO_DAS",exist_ok=True)
print(os.system('dir'))
sampath =r'C:\Users\WELCOME\Pictures\Camera Roll'
print(path.exists(sampath))
print(path.basename(sampath))
print(path.expanduser('~\~/BEN10'))
print(path.dirname(sampath))
print(os.getcwd())
print(os.getlogin())
os.chdir(r'C:\Users\WELCOME\Desktop\Python\LEO_DAS')
print(os.getcwd())
# os.makedirs(name="LEO",exist_ok=True)
# os.rename('LEO',"LEO_DASS")
# os.removedirs('LEO_DASS')
# os.startfile("https://github.com/Prawinkumarjs")
with open('file1.txt','w') as  d:d.write("Yuvaraj anne payaluga! kodurama")
# os.link('file1.txt','file1backup.txt')
with open('file1.txt','a') as  d:d.write("\nRanga oru kutty *****")
with open('file1.txt','r') as r:print(r.read())
print(os.cpu_count())
